### ISSUE TITLE
DriverInterface.php file

### ISSUE THREAD

**Issue by MortezaAttari** [kavehs87/phpIBSngApi#1]
The file "Library/DriverInterface.php" dosen't exist.

**Comment by kavehs87** [comment]
remove line 
include 'Library/DriverInterface.php';
from bootstrap.php

**Comment by peyman69tricks** [comment]
:) removed and now where is DriverInterface????

**Comment by peyman69tricks** [comment]
Interface 'radiusApi\DriverInterface' not found
